package boursier.louis.hermeez.backend;

import boursier.louis.hermeez.backend.entities.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

/**
 * Matches specified urls to manually defined functions in the service class {@link boursier.louis.hermeez.backend.CustomizedUserService}.
 * Urls auto generated by MongoRepository for CRUD on entity object do not appear here. See {@link boursier.louis.hermeez.backend.UserRepository}.
 */

@RestController
public class Controller {

    @Autowired
    private CustomizedUserService userService;

    @GetMapping(path = "/findByLastNameAndFirstName")
    public List<User> findByNameAndFirstName(@RequestParam(value = "lastName") String lastName,
                                             @RequestParam(value = "firstName") String firstName) {
        return userService.findByNameAndFirstName(lastName, firstName);
    }

}
